### ISSUE TITLE
npm package

### ISSUE THREAD

**Issue by nebulaOW** [Zezombye/overpy#394]
Hi, I would love an npm package for this project for use with CI/CD (GitHub Actions) and to use in websites if I need to compile/decompile something from user code.

**Comment by Teakowa** [comment]
Great! Now OverPy not only supports JS/TS, but also CLI calls! We can check more details in the documentation: [npm-usage](https://github.com/Zezombye/overpy?tab=readme-ov-file#npm-usage). 

In my case, I created package.json and then called it in GitHub Action:
```json
{
  "name": "bastion",
  "private": true,
  "version": "1.0.0",
  "description": "Build tooling for OverPy workshop outputs",
  "scripts": {
    "build:main": "overpy compile -i src/main.opy -o build/main.ow -l en-US",
    "build:dev": "overpy compile -i src/devMain.opy -o build/devMain.ow -l en-US",
    "build:main:en": "overpy compile -i src/main.opy -o build/main.en-US.ow -l en-US",
    "build:dev:en": "overpy compile -i src/devMain.opy -o build/devMain.en-US.ow -l en-US",
    "build:main:zh": "overpy compile -i src/main.opy -o build/main.zh-CN.ow -l zh-CN",
    "build:dev:zh": "overpy compile -i src/devMain.opy -o build/devMain.zh-CN.ow -l zh-CN",
    "build:release": "pnpm run build:main:en && pnpm run build:dev:en && pnpm run build:main:zh && pnpm run build:dev:zh",
    "build": "pnpm run build:main && pnpm run build:dev"
  },
  "dependencies": {
    "overpy": "^9.4.21"
  }
}
```

```yml
name: CI Build Check

on:
  pull_request:

jobs:
  overpy-build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Setup pnpm
        uses: pnpm/action-setup@v4

      - name: Setup Node.js
        uses: actions/setup-node@v6
        with:
          cache: pnpm

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Build with OverPy
        run: pnpm run build

```

Now overpy has more possibilities, for example, after CI compile, it can auto shares to the community via a Discord bot!
